### ISSUE TITLE
[IDEA] - Bonk Command

### ISSUE THREAD

**Issue by AleixFerre** [AleixFerre/CataBot#119]
Timeout similar command.

Give special role that can do less than @everyone and timeout him for a certain amount of time.

**Comment by CatalaHD** [comment]
S'ha de guardar PER CADA SERVIDOR:
 - [ ] El nom del rol de bonked [ string ]
 - [ ] El nom del canal de veu al que s'ha de moure [ string ] (optional)

**Comment by CatalaHD** [comment]
- [ ] Guardar a la BD el nou model
- [ ] Mostrar-lo a `!server`
- [ ] Fer una comanda `!bonk < user >` que tregui tots els rols que té i li doni el rol de `bonked`.

**Comment by AleixFerre** [comment]
Fumada no escalable, closing
