### ISSUE TITLE
[OPTIMIZATION] - Masses crides a la Base de Dades al entrar i sortir d'un servidor

### ISSUE THREAD

**Issue by AleixFerre** [AleixFerre/CataBot#141]
Es fa una crida per cada usuari per un insert en ves d'un insertMany quan el bot entra a un servidor nou

https://docs.mongodb.com/manual/reference/method/db.collection.insertMany/

**Comment by CatalaHD** [comment]
També es podria aplicar el mateix al **onGuildRemove**
Ja que s'esborra per cada usuari independentment. Es podria fer instantàniament amb una sola crida amb https://docs.mongodb.com/manual/reference/method/db.collection.deleteMany/

**Comment by CatalaHD** [comment]
TODO:
- [ ] Quan el bot entra a un servidor nou i ha de crear tots els usuaris.
- [ ] Quan el bot surt d'un servidor i ha d'esborrar tots els usuaris.

**Comment by AleixFerre** [comment]
La idea seria:
```
Esborrar tots els USUARIS que segueixin que:
 - IDs.serverID is equal to guild.id
```

**Comment by AleixFerre** [comment]
Es parla de tot a la https://github.com/AleixFerre/CataBot/issues/146
