### ISSUE TITLE
[IDEA] - Spam command set

### ISSUE THREAD

**Issue by AleixFerre** [AleixFerre/CataBot#97]
2  o 3 comandes: 
 * Una per guardar la info del perfil de twitch o youtbue i el necessari per generar el missatge
 * Una per avisar al servidor que s'escolleix que mostri el perfil al canal de spam
 * Una comanda per posar el canal de spam (també es podria posar al canal d'avisos)

**Comment by CatalaHD** [comment]
A la info del perfil de spam ja es podria guardar la llista de servidors que es vol enviar el spam, llavors quan s'envii la comanda per algun lloc on el bot ho vegi, llegirà la llista i la recorrerà enviant el missatge a tots.

Per escollir els servidors, la llista que es mostrarà serà la que comparteixen l'usuari i el bot i es mostrarà amb uns index que l'usuari haurà d'escollir. Per exemple:

```
LLISTA DE CANALS:
1 Server1
2 Server2
3 Server3
```

I l'usuari posa:
`3 1`

I el bot registra la informació en un array d'enters
